### ISSUE TITLE
 Is there a way to use SudachiDict with Kagome?

### ISSUE THREAD

**Issue by u-nation** [ikawaha/kagome-dict#47]
If it's out of place to ask, I apologize.

Is there currently a way to use [SudachiDict](https://github.com/WorksApplications/SudachiDict) with Kagome?

If not, I would appreciate any advice on how this could be achieved.

Although my understanding is still limited, could it be possible to achieve this by creating something that can parse csv formats tailored to SudachiDict, similar to the repositories below?
https://github.com/ikawaha/kagome-dict-ipa-neologd
https://github.com/ikawaha/kagome-dict-uni3

**Comment by ikawaha** [comment]
Hi,

kagome does not currently support sudachi dictionaries.

As you mentioned, it is possible to simply use sudachi's dictionaries like any other dictionary by parsing the csv. However, the functions of sudachi's dictionaries (A-mode, B-mode, C-mode, etc.) are not supported by the parsing side, so they cannot be used.

The sudachi dictionary is based on unidic, so if you use unidic, the result will be similar to using a simple sudachi dictionary.

I hope that answers your question. Thank you.

P.S.
There seems to be a Go port of sudachi: https://github.com/msnoigrs/gosudachi

**Comment by u-nation** [comment]
Thank you for the answer, I understood.

Best regards.
