### ISSUE TITLE
feat: Name field in dict.Dict struct for dictionary name

### ISSUE THREAD

**Issue by KEINOS** [ikawaha/kagome-dict#49]
I want to add `Name` field for a dictionary name as an ID.

```diff
type Dict struct {
	Morphs       Morphs
	POSTable     POSTable
	ContentsMeta ContentsMeta
	Contents     Contents
	Connection   ConnectionTable
	Index        IndexTable
	CharClass    CharClass
	CharCategory CharCategory
	InvokeList   InvokeList
	GroupList    GroupList
	UnkDict      UnkDict
+	Name         string
}
```

Since POS info varies between dictionaries, enabling to retrieve dictionary name is useful for changing the behavior depending on the dictionary.
```go
// import (
//   "github.com/ikawaha/kagome-dict/dict"
//   "github.com/ikawaha/kagome-dict/ipa"
//   "github.com/ikawaha/kagome/v2/tokenizer"
// )

sysDict := ipa.Dict()
fmt.Println(sysDict.Name)

tkn, _ := tokenizer.New(sysDict, tokenizer.OmitBosEos())
fmt.Println(tkn.DictName())

// Output:
// IPA
// IPA
```

If it sounds OK, I would like to PR this.

**Comment by ikawaha** [comment]
It seems very good! 👍  Thank you!

**Comment by ikawaha** [comment]
@KEINOS

Hi,

Your contribution has been invaluable, and I'm pleased to inform you that we have successfully merged your PR and included it in our latest release.

* https://github.com/ikawaha/kagome-dict/releases/tag/v1.1.0
* https://github.com/ikawaha/kagome/releases/tag/v2.9.9

If you have any more ideas or suggestions, please do not hesitate to share them. We look forward to your continued contributions and collaboration.

Thank you once again for your excellent work!
